version: '3.8'

services:

  keycloak:
      image: quay.io/keycloak/keycloak:22.0.1
      container_name: auth_keycloak
      command: start-dev --import-realm # add import
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
        - "8080:8080"
      volumes:
        - ./keycloak-config:/opt/keycloak/data/import